# Generated by Django 5.1.1 on 2024-09-26 23:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a purpose of tool', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tool', models.CharField(help_text='Tools type', max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description', max_length=1000)),
                ('brand_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand')),
                ('purpose', models.ManyToManyField(help_text='Select a purpose for this tool', to='catalog.purpose')),
            ],
        ),
        migrations.CreateModel(
            name='ToolUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for tools unit from the catalog', primary_key=True, serialize=False)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Tool availability', max_length=1)),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.tool')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
