# Generated by Django 5.1.1 on 2024-09-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='toolunit',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
