# Generated by Django 5.1.1 on 2024-10-09 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_brand_serial_number_toolunit_serial_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_name']},
        ),
        migrations.AddField(
            model_name='toolunit',
            name='borower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='toolunit',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Enter a serial number', max_length=20, null=True),
        ),
    ]
