# Generated by Django 5.1.1 on 2024-10-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_brand_options_toolunit_borower_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolunit',
            old_name='borower',
            new_name='borrower',
        ),
    ]
