# Generated by Django 5.1.1 on 2024-10-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_borower_toolunit_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolunit',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
