# Generated by Django 5.1.1 on 2024-10-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_tool_brand_name_toolunit_brand_name_and_more'),
        ('catalog', '0006_toolunit_brand_name_alter_toolunit_status'),
    ]

    operations = [
    ]
