# Generated by Django 5.1.1 on 2024-10-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_toolunit_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='description',
        ),
        migrations.AddField(
            model_name='toolunit',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a brief description', max_length=1000, null=True),
        ),
    ]
