# Generated by Django 5.1.1 on 2024-10-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_tool_description_toolunit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolunit',
            name='tool_name',
            field=models.CharField(blank=True, help_text='Enter a tool name', max_length=200, null=True),
        ),
    ]
