# Generated by Django 5.1.1 on 2024-10-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_toolunit_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolunit',
            options={'ordering': ['status'], 'permissions': (('can_mark_returned', 'Set tool as returned'),)},
        ),
    ]
